# Generated by Django 4.2 on 2023-05-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0002_alter_score_evaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="finish",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="score",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
    ]
