# Generated by Django 4.2 on 2023-05-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="user_id",
            field=models.IntegerField(default=1001),
        ),
    ]
