# Generated by Django 4.2 on 2023-05-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("scores", "0001_initial"),
        ("answers", "0002_alter_answer_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="score",
            field=models.ForeignKey(
                default=31,
                on_delete=django.db.models.deletion.CASCADE,
                to="scores.score",
            ),
            preserve_default=False,
        ),
    ]
