# Generated by Django 4.2 on 2023-05-10 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("answers", "0003_answer_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="score",
        ),
    ]
