# Generated by Django 4.2 on 2023-05-15 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions_options", "0002_alter_questionoption_question"),
        ("answers", "0005_answer_evaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="questions_options.questionoption",
            ),
        ),
    ]
